### ISSUE TITLE
Doesn't this miss the obvious non-timing attack?

### ISSUE THREAD

**Issue by domenic** [hillbrad/sri-addressable-caching#1]
The user visits evil.com, which contains the following line:

``` html
<script src="/probe.js" integrity="sha-256:hash-of-bank.com's-data" />
```

The evil.com server then tells the page whether or not it received a request. If it received the request, then the user has never been to bank.com, or has not been to bank.com with the specific script data that was hashed. If the request is never received, then the user has been to bank.com with that data.

(I think this can also be accomplished without server collaboration: if probe.js sets a global variable, then the presence of the global means that bank.com has not been visited, whereas its absence means bank.com has been visited in the past.)

This is not really a timing attack, but a 100% privacy leak. It seems worthwhile to mention it in the document.

**Comment by hillbrad** [comment]
https://github.com/hillbrad/sri-addressable-caching/commit/82ee28af9f83c1db1f650a2a0d1944982d429f3c

**Comment by hillbrad** [comment]
https://github.com/hillbrad/sri-addressable-caching/commit/d96a5c80fd58b0b557eb135374f575fe7fa83610
