### ISSUE TITLE
Origin laundering mitigation

### ISSUE THREAD

**Issue by yoavweiss** [hillbrad/sri-addressable-caching#4]
Would it be possible to mitigate origin laundering if SRI based cached resources would also contain a list of past URLs this resource was fetched from? 

That way, CSP could be validated against that list of URLs, and if none passes CSP, the resource would not be fetched from cache.

If a resource was served from cache, the current URL won't be added to the list of URLs associated with the resource until the browser would asynchronously validate the hash for that URL.

(Such an implementation might have significant memory and runtime costs, as it would need to keep a list of URLs with each resources and compare CSP to all of them. There might be ways this could be optimized away though)

Alternatively, we could also say that SRI based caching will not be used for sites that deploy CSP unless they also [whitelist](https://w3c.github.io/webappsec-csp/#external-hash) those particular hashes.

**Comment by hillbrad** [comment]
## I believe this is already covered:

Managing origin laundering is a bit more difficult, but only requires the cache to
be annotated with a list of the most popular sources (including path) for a given
resource, and double-keying the content addressable cache with both the resource hash
and its path.  Either a crawling or user telemetry based cache population strategy
provides the necessary data for this double-keying.

In many circumstances, it may be possible to safely load from the content addressable
cache using only the hash key, for example:

```
* If no Content-Security-Policy rules apply to the resource fetch<
* If a resource's Content-Security-Policy header explicitly lists the hash 
    of an external resource as allowed, that could be interpreted as an authoritative
    statement that its origin provenance is irrelevant
* If the origin provenance of a resource is otherwise irrelevant because the
    resource is not granted any special privileges based on that information
```
